codecov:
  require_ci_to_pass: yes

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: yes
      method: no
      macro: no

coverage:
  precision: 2
  round: down
  range: "90...100"

ignore:
  - "src/test" # ignore folders and all its contents
  - "src/*.ts" # glob accepted

github_checks:
  annotations: true
