environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true
  nodejs_version: "6"

branches:
  only:
    - master

image: Visual Studio 2015

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - set path=%programfiles(x86)%\\Microsoft SDKs\TypeScript\2.4;%path%

build_script:
  - npm run vscode:prepublish

test_script:
  - npm run test

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/bb4990244c63e96e6cb9
    method: GET